apiVersion: apps/v1
kind: Deployment
metadata:
  name:  agileDeployment
  namespace: demo
spec:
  selector:
    matchLabels:
      app: agileDeployment
  template:
    metadata:
      labels:
        app: agileDeployment
    spec:
      containers:
        - name: agileDeployment
          image: shorol/scrum-dhaka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000