apiVersion: apps/v1
kind: Deployment
metadata:
  name:  agile-deployment
  namespace: demo
spec:
  selector:
    matchLabels:
      app: agile-deployment
  template:
    metadata:
      labels:
        app: agile-deployment
    spec:
      containers:
        - name: agile-deployment
          image: shorol/scrum-dhaka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000