apiVersion: v1
kind: Service
metadata:
  name:  agileDeployment
  namespace: demo
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: agileDeployment